// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaC0dGJ1BvFfTAKUBtcyu02QaakIL-lP0',
    appId: '1:672263626078:android:2dd6ac60e16f8b37c303cf',
    messagingSenderId: '672263626078',
    projectId: 'fir-login-588d4',
    storageBucket: 'fir-login-588d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAabyWABw40Pg1rEBvLbO3OG8aFZTwc3xA',
    appId: '1:672263626078:ios:d959e9ca9aec36aac303cf',
    messagingSenderId: '672263626078',
    projectId: 'fir-login-588d4',
    storageBucket: 'fir-login-588d4.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAabyWABw40Pg1rEBvLbO3OG8aFZTwc3xA',
    appId: '1:672263626078:ios:d959e9ca9aec36aac303cf',
    messagingSenderId: '672263626078',
    projectId: 'fir-login-588d4',
    storageBucket: 'fir-login-588d4.appspot.com',
    iosBundleId: 'com.example.project',
  );

}